# Generated by Django 4.0.4 on 2023-12-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_image_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expire_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
