# Generated by Django 4.0.4 on 2023-12-06 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_image', to='main.item'),
        ),
    ]
